server:
  port: 8080

spring:
  application:
    name: dya-backend
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  prices:
    baseUrl: ${COINGECKO_BASE_URL:https://api.coingecko.com/api/v3}
    cacheTtlMinutes: ${PRICE_CACHE_TTL_MINUTES:10}
    demoApiKey: ${COINGECKO_DEMO_API_KEY:}
    refreshMinutes: ${PRICE_REFRESH_MINUTES:0}
  http:
    connectTimeoutMillis: 3000
    readTimeoutMillis: 4000
    proxyHost: ${HTTP_PROXY_HOST:}
    proxyPort: ${HTTP_PROXY_PORT:0}
  chains:
    ethereum:
      rpcUrl: ${ETHEREUM_RPC_URL:} # Alchemy/Infura HTTPS
      wsUrl:  ${ETHEREUM_WS_URL:}  # optional for later
      chainId: 1
      infuraApiKey: ${INFURA_API_KEY:}
